from sqlalchemy import text
from backend.core.database import engine, SessionLocal, get_db, Base


def test_database_connection():
    with engine.connect() as conn:
        result = conn.execute(text("SELECT 1")).scalar()
        assert result == 1


def test_session_lifecycle():
    gen = get_db()
    session = next(gen)
    try:
        assert session.is_active
        result = session.execute(text("SELECT 1")).scalar()
        assert result == 1
    finally:
        try:
            next(gen)
        except StopIteration:
            pass


def test_base_metadata():
    assert Base.metadata is not None


def test_all_v2_1_tables_in_base_metadata():
    """Verify that SQLAlchemy Base metadata contains all 9 V2.1 tables."""
    expected_tables = {
        "users",
        "workspaces",
        "workspace_members",
        "documents",
        "document_chunks",
        "conversations",
        "messages",
        "memories",
        "ingestion_jobs",
    }
    actual_tables = set(Base.metadata.tables.keys())
    assert expected_tables.issubset(actual_tables), f"Missing tables: {expected_tables - actual_tables}"


def test_alembic_current_revision_is_head():
    """Verify Alembic migration state matches latest head."""
    from alembic.config import Config
    from alembic.script import ScriptDirectory
    from alembic.runtime.migration import MigrationContext

    cfg = Config("alembic.ini")
    script = ScriptDirectory.from_config(cfg)
    heads = script.get_heads()
    assert len(heads) == 1
    head_rev = heads[0]
    assert head_rev == "8b09e014fdae"

    with engine.connect() as conn:
        ctx = MigrationContext.configure(conn)
        current_rev = ctx.get_current_revision()
        assert current_rev == head_rev


def test_alembic_no_schema_drift():
    """Verify zero unmigrated schema drift using Alembic check."""
    from alembic.config import Config
    from alembic import command

    cfg = Config("alembic.ini")
    # command.check raises AutogenerateDiffsDetected if changes detected
    command.check(cfg)


def test_alembic_upgrade_downgrade_cycle_safe():
    """
    Verify migration upgrade and downgrade scripts execute cleanly without modifying public user data.
    Generates and validates full forward and backward transactional DDL scripts through Alembic.
    """
    import io
    from contextlib import redirect_stdout
    from alembic.config import Config
    from alembic import command
    from alembic.script import ScriptDirectory

    cfg = Config("alembic.ini")
    script = ScriptDirectory.from_config(cfg)
    heads = script.get_heads()
    assert len(heads) == 1
    head_rev = heads[0]

    # 1. Forward migration (upgrade to head)
    buf_up = io.StringIO()
    with redirect_stdout(buf_up):
        command.upgrade(cfg, "head", sql=True)
    up_sql = buf_up.getvalue()

    expected_create_tables = {
        "CREATE TABLE users",
        "CREATE TABLE workspaces",
        "CREATE TABLE workspace_members",
        "CREATE TABLE documents",
        "CREATE TABLE document_chunks",
        "CREATE TABLE conversations",
        "CREATE TABLE messages",
        "CREATE TABLE memories",
        "CREATE TABLE ingestion_jobs",
    }
    for stmt in expected_create_tables:
        assert stmt in up_sql, f"Missing DDL statement in upgrade: {stmt}"
    assert (
        f"INSERT INTO alembic_version (version_num) VALUES ('{head_rev}')" in up_sql
        or f"UPDATE alembic_version SET version_num='{head_rev}'" in up_sql
    )

    # 2. Reversal migration (downgrade to base)
    buf_down = io.StringIO()
    with redirect_stdout(buf_down):
        command.downgrade(cfg, f"{head_rev}:base", sql=True)
    down_sql = buf_down.getvalue()

    expected_drop_tables = {
        "DROP TABLE users",
        "DROP TABLE workspaces",
        "DROP TABLE workspace_members",
        "DROP TABLE documents",
        "DROP TABLE document_chunks",
        "DROP TABLE conversations",
        "DROP TABLE messages",
        "DROP TABLE memories",
        "DROP TABLE ingestion_jobs",
    }
    for stmt in expected_drop_tables:
        assert stmt in down_sql, f"Missing DDL statement in downgrade: {stmt}"
    assert (
        f"DELETE FROM alembic_version WHERE alembic_version.version_num = '{head_rev}'" in down_sql
        or f"WHERE alembic_version.version_num = '{head_rev}'" in down_sql
    )
